# Generated by Django 3.1.7 on 2021-03-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_braintree_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',)},
        ),
    ]
